[package]
edition = "2021"
name = "task-one"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-serde = {path = "./my-serde", features = ["derive"]}
