[package]
name = "box_example_7_2"
version = "0.1.0"
authors = ["custer-go <custertian@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
